### ISSUE TITLE
Homepage design

### ISSUE THREAD

**Issue by sleekLancelot** [BuildForSDGCohort2/Team-050-Group-A-FrontEnd#2]
Create a home/landing page design.

**Comment by Timmymichael** [comment]
Here is a figma link to the prototype of the landing page.
![Landing Page](https://user-images.githubusercontent.com/24977208/91642614-b8e59f80-ea24-11ea-86b9-e8bb00e0e1f3.png)

**Comment by sleekLancelot** [comment]
> Here is a figma link to the prototype of the landing page.
> ![Landing Page](https://user-images.githubusercontent.com/24977208/91642614-b8e59f80-ea24-11ea-86b9-e8bb00e0e1f3.png)

Will start working with this

**Comment by sleekLancelot** [comment]
@Timmymichael please change the logo name to Crimistry!

**Comment by Timmymichael** [comment]
Okay

**Comment by Timmymichael** [comment]
Incase you need these (The logos in SVG format)
