### ISSUE TITLE
Build wireframes for remaining pages

### ISSUE THREAD

**Issue by sleekLancelot** [BuildForSDGCohort2/Team-050-Group-A-FrontEnd#4]
login page wireframe for admin and citizen with responsive designs
 Profile page wireframe for admin and citizen with responsive designs

**Comment by Timmymichael** [comment]
I'm on it.

**Comment by Timmymichael** [comment]
Login and Signup page. Note: there is an updated footer for the homepage.
https://www.figma.com/file/h1dIPUTnNzLnmhvMrpnKL9/Criminal-Registry?node-id=0%3A1
![Login Page](https://user-images.githubusercontent.com/24977208/92269717-9d730c80-eedc-11ea-915b-7e86647a9b38.png)
![Signup Page](https://user-images.githubusercontent.com/24977208/92269722-a06dfd00-eedc-11ea-975c-849e5a5201b8.png)

**Comment by Timmymichael** [comment]
Dashboard of the user has now been completed
https://www.figma.com/file/h1dIPUTnNzLnmhvMrpnKL9/Criminal-Registry?node-id=0%3A1
![Dashboard(User)](https://user-images.githubusercontent.com/24977208/92954924-288e5e00-f419-11ea-9023-f588f746df13.png)
